#ifndef RISCV_DEFS_H
#define RISCV_DEFS_H

// CSR addresses
#define MSTATUS_ADDR 0x300
#define MTVEC_ADDR 0x305
#define MSCRATCH_ADDR 0x340
#define MEPC_ADDR 0x341
#define MCAUSE_ADDR 0x342
#define MTVAL_ADDR 0x343
#define MCYCLE_ADDR 0xb00
#define MINSTRET_ADDR 0xb02
#define MCYCLEH_ADDR 0xf80
#define MINSTRETH_ADDR 0xf82
#define MIE_ADDR 0x304
#define MIP_ADDR 0x344
#define FFLAGS_ADDR 0x001
#define FRM_ADDR 0x002
#define FCSR_ADDR 0x003

// mie
#define MIE_MSIE_bp 3
#define MIE_MTIE_bp 7
#define MIE_MEIE_bp 11
#define MIE_MSIE (1 << MIE_MSIE_bp)
#define MIE_MTIE (1 << MIE_MTIE_bp)
#define MIE_MEIE (1 << MIE_MEIE_bp)

// mip
#define MIP_MSIP_bp 3
#define MIP_MTIP_bp 7
#define MIP_MEIP_bp 11
#define MIP_MSIP (1 << MIP_MSIP_bp)
#define MIP_MTIP (1 << MIP_MTIP_bp)
#define MIP_MEIP (1 << MIP_MEIP_bp)

// mstatus
#define MSTATUS_MIE_bp 3
#define MSTATUS_MIE (1 << MSTATUS_MIE_bp)

#define MSTATUS_MPIE_bp 7
#define MSTATUS_MPIE (1 << MSTATUS_MPIE_bp)

// mtvec
#define MTVEC_MODE_bp 0
#define MTVEC_MODE_DIRECT 0x0
#define MTVEC_MODE_VECTORED 0x1


#define MTVEC_BASE_bp 2
#define MTVEC_BASE_bm 0x7fffffff

// mcause
#define MCAUSE_INTERRUPT_bp 31
#define MCAUSE_INTERRUPT_bm (1 << MCAUSE_INTERRUPT_bp)
#define MCAUSE_INTERRUPT_INTERRUPT MCAUSE_INTERRUPT_bm
#define MCAUSE_INTERRUPT_EXCEPTION 0x0

#define MCAUSE_CODE_bp 0
#define MCAUSE_CODE_bm (0xffffffff >> 1)

#define MCAUSE_CODE_INT_U_SOFTWARE 0
#define MCAUSE_CODE_INT_S_SOFTWARE 1
#define MCAUSE_CODE_INT_M_SOFTWARE 3

#define MCAUSE_CODE_INT_U_TIMER 4
#define MCAUSE_CODE_INT_S_TIMER 5
#define MCAUSE_CODE_INT_M_TIMER 7

#define MCAUSE_CODE_INT_U_EXTERNAL 8
#define MCAUSE_CODE_INT_S_EXTERNAL 9
#define MCAUSE_CODE_INT_M_EXTERNAL 11

#define MCAUSE_CODE_INT_RESERVED_PLATFORM 16

#define MCAUSE_CODE_EX_INST_MISALIGNED 0
#define MCAUSE_CODE_EX_INST_ACCESS 1
#define MCAUSE_CODE_EX_ILLEGAL_INST 2
#define MCAUSE_CODE_EX_BREAKPOINT 3
#define MCAUSE_CODE_EX_LOAD_MISALIGNED 4
#define MCAUSE_CODE_EX_LOAD_FAULT 5
#define MCAUSE_CODE_EX_STORE_MISALIGNED 6
#define MCAUSE_CODE_EX_STORE_FAULT 7
#define MCAUSE_CODE_EX_ECALL_U 8
#define MCAUSE_CODE_EX_ECALL_S 9
#define MCAUSE_CODE_EX_ECALL_M 11
#define MCAUSE_CODE_EX_INST_PAGE_FAULT 12
#define MCAUSE_CODE_EX_LOAD_PAGE_FAULT 13
#define MCAUSE_CODE_EX_STORE_PAGE_FAULT 15

#endif